#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server using scp
# The variable $0 is the script's name. The total number of arguments is stored in $#.

if [[ "$#" -ne '4' ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
fi
