#!/usr/bin/env bash
# Write a Bash script that generates a MySQL dump and creates a compressed archive out of it.

mysqldump -u root -p $1 > backup.sql
date='date +%m-%d-%Y'
tar -czvf date.tar.gz ./backup.sql
