#!/usr/bin/env bash
# Write a script that plays with signal traps.

trap "echo I hate the kill command; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT

echo $$ > /var/run/holbertonscript.pid
while :
do
	echo "To infinity and beyond"
done
