#!/usr/bin/env bash
#This script prints bad luck, good luck, and holbertson school in a 10x loop

i=0

while [ $i -le 9 ]
do
	if [[ "$i" == '3' ]]; then
		echo "bad luck"

	elif [[ "$i" == '7' ]]; then
		echo "good luck"

	else	
		echo "Holberton School"
	fi

	((i++))
done
