#!/usr/bin/env bash
#This script loops 20x with iterator and bad luck by country

i=1

while [ $i -le 20 ]
do
	echo $i
	case "$i" in

		4)
			echo "bad luck from China"
			;;

		9)
			echo "bad luck from Japan"
			;;

		17)
			echo "bad luck from Italy"
			;;
	esac
	((i++))
done
