#!/usr/bin/env bash
#This script prints 12 hours and 59 minutes in order with while loops

i=0

while [ $i -le 12 ]
do
	j=1
	echo "Hour:" $i
	while [ $j -le 59 ]
	do
		echo $j
		((j++))
	done

	((i++))
done
